### ISSUE TITLE
Composer killed

### ISSUE THREAD

**Issue by Ferror** [Serwild/docker#3]
<img width="589" alt="Screenshot 2019-11-07 at 21 31 37" src="https://user-images.githubusercontent.com/17534504/68425269-0b0fb880-01a6-11ea-98c3-28ea97cf5e7b.png">

**Comment by Dr4il** [comment]
Logs?

**Comment by Ferror** [comment]
Zwiększyłem dockerowi ilość ramu i zadziałało wczoraj, więc do zamknięcia
